<a href="https://colab.research.google.com/github/profteachkids/CHE5136_Fall2022/blob/main/Linear_NonLinear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
from plotly.subplots import make_subplots
from scipy.optimize import minimize

In [8]:
rng=np.random.RandomState(123)
N=50
x_data = np.linspace(-5.,5., N)
y_data = rng.normal(loc=2.*x_data +1., scale=0.4)

In [10]:
def sumsq(u):
    m,b = u
    return np.sum( (y_data - (m*x_data + b))**2)

In [15]:
minimize(sumsq, [0.,0.]).x

array([2.01526623, 1.00530857])

In [9]:
fig = make_subplots()
fig.add_scatter(x=x_data, y=y_data, mode='markers')
fig.update_layout(width=600, height=600, template='plotly_dark')

In [4]:
A = np.c_[x_data, np.ones_like(x_data)]
J=A.T @ A

In [5]:
m,b = np.linalg.solve(A.T@A, A.T @ y_data)

In [16]:
m,b

(2.015266236744091, 1.0053085764335146)

In [6]:
fig = make_subplots()
fig.add_scatter(x=x_data, y=y_data, mode='markers')
fig.add_scatter(x=x_data, y=m*x_data+b, mode='lines')
fig.update_layout(width=600, height=600, template='plotly_dark')


In [41]:
N=30
xd=np.linspace(-1.,1., N)
A = np.c_[xd**4, xd**3, xd**2, xd, np.ones_like(xd)]
yd = 1.2*(xd-0.9)*(xd-0.3)*(xd+0.4)*(xd+0.8)
yd = rng.normal(loc=yd, scale=0.02)

In [42]:
def sqerr(u):
    model = A @ u

    return np.sum((yd -model)**2)

In [43]:
u_min = minimize(sqerr, np.zeros(5)).x

In [44]:
fig = make_subplots()
fig.add_scatter(x=xd, y=yd, mode='markers')
fig.add_scatter(x=xd, y=A @ u_min, mode='lines')
fig.update_layout(width=600, height=600, template='plotly_dark')

In [46]:
u_linalg = np.linalg.solve(A.T @ A, A.T @ yd)

In [47]:
u_linalg

array([ 1.22036498,  0.03694644, -1.03278048, -0.0959974 ,  0.10624321])

In [48]:
u_min

array([ 1.22036464,  0.03694889, -1.03278025, -0.09599908,  0.1062432 ])

In [ ]:
fig = make_subplots()
fig.add_scatter(x=xd, y=yd, mode='markers')
fig.add_scatter(x=xd, y=A @ u_min, mode='lines')
fig.update_layout(width=600, height=600, template='plotly_dark')

In [65]:
N=100
xd=np.linspace(0,9., N)
yd = 1.2*np.exp(-xd/2)*np.sin(6.*xd)
yd = rng.normal(loc=yd, scale=np.abs(0.1*yd))

fig = make_subplots()
fig.add_scatter(x=xd, y=yd, mode='markers')
fig.update_layout(width=600, height=600, template='plotly_dark')

In [66]:
def sumsq(u):
   a, td, w = u
   ym = a*np.exp(-xd/td)*np.sin(w*xd)
   return np.sum((ym-yd)**2)

In [69]:
a, td, w= minimize(sumsq, [1., 1., 5.]).x

In [72]:
xm = np.linspace(0, 9.,500)

fig = make_subplots()
fig.add_scatter(x=xd, y=yd, mode='markers')
fig.add_scatter(x=xm, y= a*np.exp(-xm/td)*np.sin(w*xm), mode='lines')
fig.update_layout(width=600, height=600, template='plotly_dark')