<a href="https://colab.research.google.com/github/profteachkids/CHE5136_Fall2022/blob/main/SecantNewton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import jax.numpy as jnp
import jax
from jax.config import config
config.update("jax_enable_x64", True)
from plotly.subplots import make_subplots

In [2]:
def f(x):
    return 0.5*(x-0.8)*(x-0.3)*(x+0.5)

In [5]:
xplot = np.linspace(-0.7,1.,100)
fig=make_subplots()
fig.add_scatter(x=xplot, y=f(xplot), mode='lines')
fig.update_layout(width=600,height=600,template='plotly_dark')

In [8]:
def secant(f, x0, x1, maxiter=50, tol=1e-12):
    f0=f(x0)
    f1=f(x1)
    xylist=[[x0,f0], [x1,f1]]
    for i in range(maxiter):
        x2 = (x1-x0)/(f0-f1)*f1 +x1
        f2 = f(x2)
        xylist.append([x2,f2])
        if abs(f2)<tol:
            break
        x0, f0 = x1, f1
        x1, f1 = x2, f2
    return x2, f2, np.array(xylist)

In [9]:
secant(f, 0., 0.5)

(0.3000000000000018,
 -3.6637359812630124e-16,
 array([[ 0.00000000e+00,  6.00000000e-02],
        [ 5.00000000e-01, -3.00000000e-02],
        [ 3.33333333e-01, -6.48148148e-03],
        [ 2.87401575e-01,  2.54249327e-03],
        [ 3.00342789e-01, -6.85400857e-05],
        [ 3.00003080e-01, -6.15901299e-07],
        [ 2.99999999e-01,  1.58567082e-10],
        [ 3.00000000e-01, -3.66373598e-16]]))

In [22]:
def newton(f, x0, maxiter=50, tol=1e-12):
    fprime = jax.grad(f)
    f0=f(x0)
    xylist = [[x0,f0]]
    for i in range(maxiter):
        x1 = x0 - f0/fprime(x0)
        f1 = f(x1)
        xylist.append([x1,f1])
        if abs(f1)<tol:
            break
        x0,f0 =x1,f1
    return x1, f1, jnp.array(xylist)

In [23]:
newton(f,0.)

(DeviceArray(0.3, dtype=float64, weak_type=True),
 DeviceArray(-0., dtype=float64, weak_type=True),
 DeviceArray([[ 0.00000000e+00,  6.00000000e-02],
              [ 3.87096774e-01, -1.59511262e-02],
              [ 2.88931283e-01,  2.23144280e-03],
              [ 2.99916207e-01,  1.67595823e-05],
              [ 2.99999995e-01,  1.05246061e-09],
              [ 3.00000000e-01, -0.00000000e+00]], dtype=float64))

In [13]:
fprime(0.)

DeviceArray(-0.155, dtype=float64, weak_type=True)

In [24]:
def fun(x):
    return jnp.array([x[0]  + 0.5 * (x[0] - x[1])**3 - 1.0,
            0.5 * (x[1] - x[0])**3 + x[1]])

In [25]:
fun(jnp.array([0.,0.]))

DeviceArray([-1.,  0.], dtype=float64)

In [29]:
def newtonN(f,x0,maxiter=50, tol=1e-12):
    f_jac=jax.jacobian(f)
    f0 = f(x0)
    for i in range(maxiter):
        x1 = x0 - jnp.linalg.inv(f_jac(x0)) @ f0
        f1 = f(x1)
        if jnp.linalg.norm(f1)<tol:
            break
        x0, f0 = x1, f1
    return x1, f1



In [31]:
newtonN(fun, jnp.array([0.,0.]))

(DeviceArray([0.8411639, 0.1588361], dtype=float64),
 DeviceArray([ 0.00000000e+00, -5.55111512e-17], dtype=float64))